[package]
edition = "2021"
name = "zipzap"
version = "0.0.2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "zipzap"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
zipzap_integrity = { workspace = true } 
