[package]
edition = "2021"
name = "zipzap_integrity"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "zipzap_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
